---
title: "eda"
output: github_document
date: "2022-10-06"
---

```{r}
library(tidyverse)
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

```{r}
weather_df %>%
  group_by(name, month)
```




```{r}
weather_df %>%
  group_by(month) %>%
  summarize(n_obs = n())
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n())
```

Can also use `count` as an alternative
```{r}
weather_df %>%
  count(month, name = "n_obs")
```

Base R allows to use `table`, but not preferred because the result is not a dataframe; can't do next steps with it
```{r}
weather_df %>%
  pull(month) %>% 
  table
```



```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```



2x2 tables
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(count = n())
```






